name: Docker Image CI

on:
  push:
    branches: [ master, dev-v0.9 ]
  pull_request:
    branches: [ master, dev-v0.9 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag triton-docker:$(date +%s)
